### ISSUE TITLE
How to use the pylogix-api

### ISSUE THREAD

**Issue by KHDOUDI** [TheFern2/pylogix-api#1]
Hello

Please support on explaining how the api works and how can i use it.

If i execute the code i get below error:

Traceback (most recent call last):

  File "<ipython-input-4-af6af064e582>", line 53, in <module>
    app.run(debug=True, host='192.168.1.19')

  File "E:\Programme_files2\Anaconda3\lib\site-packages\flask\app.py", line 841, in run
    run_simple(host, port, self, **options)

  File "E:\Programme_files2\Anaconda3\lib\site-packages\werkzeug\serving.py", line 720, in run_simple
    s.bind((hostname, port))

OSError: [WinError 10049] L’adresse demandée n’est pas valide dans son contexte

Thank you

**Comment by TheFern2** [comment]
I apologize for not responding sooner, didn't get notified for some reason. The ip should either be localhost or an ip of your machine. What's your ip, can you run `ipconfig /all` and paste results.

Try removing all run parameters, that should run localhost on port 5000:

Run localhost on port 5000:
```
app.run()
```

Run pc ip on all the local network:
```
app.run(host='0.0.0.0')
```

Specify the host ip, if you're pc has multiple network adapters:
```
app.run(host='pc ip' )
```

I've added info on the readme for the routes to make it clear. 

Flask documentation:
https://flask.palletsprojects.com/en/1.1.x/

**Comment by KHDOUDI** [comment]
Hi,

That's a clear feedback and also helpful tutorial video.

Thanks

**Comment by TheFern2** [comment]
You're welcome. :grinning:
